docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Introduction: intro.md
site_name: Authentication middleware
site_description: 'Authentication middleware for Mezzio and PSR-7 applications'
repo_url: 'https://github.com/mezzio/mezzio-authentication'
